version: "3"

services:
  query-node:
    image: hydra-test:latest
    restart: unless-stopped
    environment:
      - DB_NAME=processor-db
      - DB_HOST=db
      - DB_USER=postgres 
      - DB_PASS=postgres
      - DB_PORT=5432
      - GRAPHQL_SERVER_HOST=localhost
      - GRAPHQL_SERVER_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - hydra-processor
    command: ["yarn", "workspace", "sample", "query-node:start:prod"]

  hydra-processor:
    image: hydra-test:latest
    restart: unless-stopped
    environment:
      - DB_NAME=processor-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - TYPEORM_DATABASE=processor-db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - GRAPHQL_SERVER_HOST=localhost 
      - GRAPHQL_SERVER_PORT=4000  
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
      - INDEXER_ENDPOINT_URL=http://hydra-indexer-gateway:4000/graphql
      - NODE_URL=ws://substrate:9944
      - PROCESSOR_POLL_INTERVAL=300 # refresh every second 
      - DEBUG=hydra-processor:*
    ports:
      - "3000:3000"
    depends_on:
      - hydra-indexer-gateway
    command: >
      sh -c "yarn workspace sample query-node:configure && \
             yarn workspace sample db:drop && \
             yarn workspace sample db:prepare && \
             yarn workspace sample db:migrate && \
             yarn workspace sample mappings:build && \
             yarn workspace sample processor:start"
  
  hydra-indexer:
    image: hydra-indexer:latest
    restart: unless-stopped
    environment:
      - DB_NAME=indexer-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - NEW_BLOCK_TIMEOUT_SEC=150000
      - WS_PROVIDER_ENDPOINT_URI=ws://substrate:9944/
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index-builder:*
    command: > 
      sh -c "yarn db:bootstrap && yarn start:prod" 
    depends_on:
      - substrate
      - redis
      - db
    
  hydra-indexer-gateway:
    image: hydra-indexer-gateway:latest
    restart: unless-stopped
    environment:
      - WARTHOG_STARTER_DB_DATABASE=indexer-db
      - WARTHOG_STARTER_DB_HOST=db 
      - WARTHOG_STARTER_DB_PASSWORD=postgres
      - WARTHOG_STARTER_DB_PORT=5432 
      - WARTHOG_STARTER_DB_USERNAME=postgres 
      - WARTHOG_STARTER_REDIS_URI=redis://redis:6379/0 
      - PORT=4000
      - DEBUG=index-server:*
    ports:
      - "4001:4000"
    depends_on:
      - redis
      - db
    
    
  substrate:
    image: paritytech/substrate-playground-template-node-template:sha-7212614
    restart: unless-stopped
    ports:
      - "9944:9944"
    command: ["./target/release/node-template", "--dev", "--tmp", "--ws-external"]

  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
    